name: Continuous integration

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        run: |
          yarn install --frozen-lockfile
          yarn validate

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build
